# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: janvince.smallrecords::lang.categories.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: JanVince\SmallRecords\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
